data_list = [
    "Selecione a voz...", 
    "Albion Online",
    "Alvin",
    "Ana",
    "Anunciador da Teleshop (Anos 90)",
    "Arlequina",
    "Arttur",
    "Athena",
    "Bafo",
    "Barack Obama (Português)",
    "Baraka",
    "Barney Rubble",
    "Ben Kenobi",
    "Bender",
    "Bob (Dono da Vinet)",
    "Braum",
    "Capitão Gancho",
    "Carl Johnson (Português)",
    "Cauê Moura (Desce a Letra)",
    "Cazum8",
    "Chapolin Colorado",
    "Chaves",
    "Chico Bento",
    "Chiquinha",
    "Cicatriz",
    "Cleiton Rasta",
    "Conde Dookan",
    "Core",
    "Coringa (Batman: A Série Animada)",
    "Coringa (Liga da Justiça)",
    "Darth Vader (Voz com Filtro)",
    "David Herick",
    "Dexter",
    "Dilma Roussef",
    "Diretor Brown (Bravo)",
    "Diretor Brown (Normal)",
    "Dona Clotilde",
    "Douglassola",
    "Doutor Chapatin",
    "Dr. Robotnik (Sonic Boom)",
    "Drawn Mask",
    "Drawn Mask (Vídeos mais antigos)",
    "Dudão",
    "Ednaldo Pereira",
    "Eneas Carneiro (Agressivo)",
    "Enormossauro",
    "Enéas Carneiro",
    "Enéas Carneiro Agressivo V2",
    "Esqueleto",
    "Faustão",
    "Faustão (Agressivo)",
    "Felps",
    "Fred Flintstone",
    "Fred Jones",
    "Gaben",
    "Gabs",
    "Galo Cego",
    "Garfield",
    "Gemaplys",
    "George Jetson",
    "Getúlio Vargas",
    "Gil Gomes",
    "Grilo Falante",
    "Gwen Tennyson",
    "Harry Potter",
    "He-Man",
    "Homer Simpson",
    "Iago",
    "Iberê Thenório (Manual do Mundo)",
    "Inspetor Bugiganga (Clubti)",
    "Ivern",
    "Jack Preto",
    "Jair Bolsonaro",
    "Junkrat",
    "Kylespark",
    "Leôncio",
    "Leôncio (1999)",
    "Leônidas",
    "Luciano Eduardo",
    "Luigi",
    "Lula",
    "Lula Molusco",
    "Margarida",
    "Mario",
    "Marlin",
    "Mercy",
    "Mestre Yoda (Prequela)",
    "Mickey Mouse",
    "Minnie Mouse",
    "Morshu (Português)",
    "Morshu Fandub",
    "MrBeast Brasil",
    "MrGuinas",
    "Mufasa",
    "Nappa",
    "Narrador Francês",
    "Narrador Globo",
    "Narrador da Biografia Toon",
    "Narrador da Peppa Pig",
    "Narrador dos DVD's",
    "Narrador dos Episódios",
    "Narradora",
    "Natanael Antonioli (Fábrica de Noobs)",
    "Nego Bam",
    "Nhonho",
    "O Odiador",
    "Orisa",
    "Orochi",
    "Otto Octavius (Doutor Octopus)",
    "Pai Troll",
    "Pai Troll (Agressivo)",
    "Papaco",
    "Pateta",
    "Pato Donald",
    "Patrick Bateman",
    "Patrick Estrela",
    "Paçoca",
    "Pernalonga",
    "Peter Turguniev (ANCAPSU)",
    "Pica Pau",
    "Policial",
    "Princesa",
    "Professor Girafales",
    "Quase Nada",
    "Quico",
    "Reaper",
    "Refúgio Mental",
    "Rei / King Harkinian (Fandub)",
    "Rei Koopa",
    "Rick Sanchez",
    "Rik Editor",
    "Roadhog",
    "Robin (The Batman 2004)",
    "Robocop",
    "Robotnik",
    "Rodrigo Faro",
    "Sabotage",
    "Saiko",
    "Salsicha",
    "Senhor Trivago",
    "Seto Kaiba",
    "Seu Barriga",
    "Seu Madruga",
    "Seu Siriguejo",
    "Shadow o Ouriço (Fandublagem)",
    "Shao Kahn",
    "Shrek",
    "Silvio Santos",
    "Smedley",
    "Souzones (HUEstation)",
    "Spy (Português)",
    "Timão",
    "Velma Dinkley",
    "Vitinho Avassalador",
    "Vô Max",
    "Wrecking Ball",
    "Zeca Urubu",
    "Zelune",
    "Zé Carioca",
    "Zé Colmeia"
]

data_dict_lower = {v.lower(): k+1 for k, v in enumerate(data_list)}

data_dict = {v: k+1 for k, v in enumerate(data_list)}
data_dict_ind = { k+1 : v for k, v in enumerate(data_list)}
